spring:
  security:
    oauth2:
      client:
        provider:
          azure-ad:
            authorization-uri: https://login.microsoftonline.com/364cc942-1cec-4791-b264-cde4a0a816f6/oauth2/v2.0/authorize
            token-uri: https://login.microsoftonline.com/364cc942-1cec-4791-b264-cde4a0a816f6/oauth2/v2.0/token
            jwk-set-uri: https://login.microsoftonline.com/364cc942-1cec-4791-b264-cde4a0a816f6/discovery/v2.0/keys
        registration:
          azure-client:
            provider: azure-ad
            client-id: 941eab4a-1e81-43f2-8305-b5cf3dc74f10
            client-secret: n7x.YIbkXUl350zYWaw.gqBXb-9q2O9_7e
            tenant-id: 364cc942-1cec-4791-b264-cde4a0a816f6
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/api/callback
            scope:  https://graph.microsoft.com/v1.0/me


#            metadata:
#              management.context-path: /actuator
#                - uri: http://instance2.intern:8080